IDEA-255927 Don't report field name if it's not registered in scheme
JetBrains/ap-validation pull request #1
Opened 2021-03-02 20:07 UTC by dymova

…scheme

2021-03-02 20:10 UTC, dymova commented on src/main/java/com/intellij/internal/statistic/eventLog/StatisticsEventEscaper.java
> +    if (Arrays.stream(ValidationResultType.values()).anyMatch(value -> str.equals(value.getDescription()))) return str;
I think it is better to save error description as is, are there any objections?

2021-03-03 17:15 UTC, SvetlanaZem requested changes

2021-03-03 17:15 UTC, SvetlanaZem commented on src/main/java/com/intellij/internal/statistic/eventLog/validator/rules/beans/EventGroupRules.java
> +          Object validateEventData = validateEventData(key + "." + entryKey, entry.getValue(), context);
Why don't you change `validateEventData` to handle both field name and value at the same time and return, for instance, a Pair? Detecting if event data field was replaced with validation.undefined_rule doesn't look stable

2021-03-04 11:16 UTC, SvetlanaZem approved these changes

2021-03-04 11:17 UTC, merged